/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Options.Options;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class KeyValidation extends javax.swing.JPanel{

    private int KeyLen;
    private int Key;
    
    //    this holds No of failure Attempt user made?
    private int attempt ;
    
    //this hold wether the account is exist or not
    boolean isExist=false;
    
    /**
     * Creates new form Welcome
     */
    public KeyValidation() {
        initComponents();
       attempt = ApplicationManager.getAttempt();
       KeyLen = 1;
//       nextButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SKey = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(88, 173, 255));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 244, 244));
        jLabel1.setText("EasyMoneyTrans");

        nextButton.setBackground(new java.awt.Color(139, 214, 255));
        nextButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 244, 244));
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Go-Button.png"))); // NOI18N
        nextButton.setText("Go");
        nextButton.setBorder(null);
        nextButton.setBorderPainted(false);
        nextButton.setContentAreaFilled(false);
        nextButton.setEnabled(false);
        nextButton.setFocusPainted(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        nextButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nextButtonKeyReleased(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(139, 214, 255));
        jSeparator1.setForeground(new java.awt.Color(139, 214, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("divider"); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/card_paypass-256png.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel5.setText("Enter Your SecretKey");

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel6.setText("Don't share Your Key with anyone ,We will never ask!!");

        SKey.setBackground(new java.awt.Color(139, 214, 255));
        SKey.setColumns(19);
        SKey.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        SKey.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SKey.setDisabledTextColor(new java.awt.Color(88, 173, 255));
        SKey.setMinimumSize(new java.awt.Dimension(2, 32));
        SKey.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SKeyFocusGained(evt);
            }
        });
        SKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SKeyKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nextButton)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(208, 208, 208))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SKey, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(189, 189, 189))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(56, 56, 56))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SKey, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel5)
                        .addGap(65, 65, 65)))
                .addGap(7, 7, 7)
                .addComponent(nextButton)
                .addGap(137, 137, 137))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        
        
               
//        ??when nextButton clicked
            
        
            try{
                System.out.println("key validation button Try");
                isExist = ApplicationManager.DBManager.c.isLoginCorrect(ApplicationManager.DBManager.cust.getAccNo(),Key);
                
                ApplicationManager.incrementAttempt();
                
                if(isExist)
                {
                  ApplicationManager.InitializeCustomer(ApplicationManager.DBManager.cust.getAccNo());
                  ApplicationManager.setAttempt(0);
                  ApplicationManager.application.loadScene(new Options()); 
                  System.out.println("successfully logedIn ");
                  
                }
                else if(attempt < 3){

                    ApplicationManager.application.loadScene(new KeyValidation());
                    ApplicationManager.Notify.sendNotification("Invalid Secret Key",1);
                    System.out.println("more then 3 attempt");
                }
                else{
                    System.out.println("invalid attempt");
                    ApplicationManager.application.loadScene(new Welcome());
                    
                    
                }
                
                
            }catch(Exception e)
            {
                System.out.println(e);
            }
        
        
    
        
        
        
        System.out.println("key validation button clicked");
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formKeyReleased

    private void nextButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nextButtonKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nextButtonKeyReleased

    private void SKeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SKeyKeyReleased
        // TODO add your handling code here:
        JPasswordField an = (JPasswordField)evt.getSource();
        
//        System.out.println("hii");
       
        try{
            if(KeyLen != 1){
               Key =  Integer.parseInt(an.getText());
            }
        }catch(Exception e)
        {
            System.out.println("error in Key");
        }
        
        KeyLen =  an.getText().length() ;
        
        if(KeyLen >= 4)
        {
            System.out.println("4 exceed");
            an.setEnabled(false);
            nextButton.setEnabled(true);
            ApplicationManager.DBManager.cust.Key=Key;
        }
    }//GEN-LAST:event_SKeyKeyReleased

    private void SKeyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SKeyFocusGained
        // TODO add your handling code here:
        ApplicationManager.Notify.hide();
    }//GEN-LAST:event_SKeyFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField SKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
